name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Update Rust
      run: curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly -y
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --all-features
    - name: Run tests
      run: cargo test --verbose --all-features
    - name: Run doc generation
      run: cargo doc --verbose --all-features
